### ISSUE TITLE
heavy performance decrease with 1.1.4

### ISSUE THREAD

**Issue by notandvm** [notrogan/FirstPersonDeath#2]
not exactly sure what exactly is causing it, as nothing is showing up in logs, but updating from 1.1.3 to 1.1.4 decently chunked framerate and general game performance

doesn't seem to be a compatibility issue with other mods as it occurs even on an empty profile with only fpd & bep; it is however **_much_** more drastic in modpacks and is how i noticed it (initially i thought this issue was from something else entirely)

**Comment by notrogan** [comment]
Hello!

This is likely related to the fact that the text in the top right indicating key binds is updated every frame, which obviously isn't very efficient. I'm not sure whether the performance hit comes from the fact that it is in a separate file from the main update method or from the use of update in general, but it should be rewritten without it regardless.

Now that I think about it, there's no reason that it should use update in the first place, as the text only needs to be edited once, so expect a patch later today.

Just to confirm, the drop came from 1.1.3 to 1.1.4, not from 1.0.3 (or previous) to 1.1.4?

**Comment by notandvm** [comment]
> Just to confirm, the drop came from 1.1.3 to 1.1.4, not from 1.0.3 (or previous) to 1.1.4?

aye yeah, occurred in 1.1.4 updating from 1.1.3

**Comment by notrogan** [comment]
Should be fixed in latest version!

Here are my performance metrics, hopefully yours look something like this:

- 1.1.3: 171fps
- 1.1.4: 63fps
- 1.1.5: 168fps

**Comment by notandvm** [comment]
yup, update seems to have fixed it! fps is back to normal & consistent levels now as of 1.1.5
