### ISSUE TITLE
Use InputUtils Instead of Config

### ISSUE THREAD

**Issue by FrostyCirno** [notrogan/FirstPersonDeath#3]
Use https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/. It is better from players' perspective than to mess around with configs. I understand if this is too much work though!

**Comment by FrostyCirno** [comment]
Also is this incompatible with https://thunderstore.io/c/lethal-company/p/coderCleric/Poltergeist/

**Comment by notrogan** [comment]
I'll look into moving it to InputUtils but no promises

**Comment by notrogan** [comment]
Using InputUtils seems to cause a noticeable performance drop, and tends to spam errors (i dont know what they refer to, nor how to fix them)

I would look into [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/). It's not a perfect solution, but it's relatively close to what you're looking for.

Personally I think that LethalConfig (or editing the config directly) is a good enough solution, but @FrostyCirno if for whatever reason that isn't an option then I can take another look at it.

**Comment by FrostyCirno** [comment]
I would prefer if LethalConfig was not a dependency. Its fine if it stays as a config, at least you tried :)

**Comment by notrogan** [comment]
I'll close this for now but I might revisit it in the future

Also, thank you for submitting bug reports! I don't have time to run around looking for bugs, so having someone find them for me is greatly appreciated :)
