### ISSUE TITLE
Water filter still applied

### ISSUE THREAD

**Issue by FrostyCirno** [notrogan/FirstPersonDeath#5]
The underwater filter is still applied when your body is in water

**Comment by notrogan** [comment]
Not able to reproduce this one... any ideas?

**Comment by FrostyCirno** [comment]
I got a screenshot of it.
1. Get a friend(s)
2. Get mine-shaft
3. Drown yourself in the pools of water
4. Switch to the other person(s)
![image](https://github.com/user-attachments/assets/5f8061d3-de16-4a57-a101-ddda87800139)
I would recommended checking if the target for spectating is in water before applying the filter

**Comment by notrogan** [comment]
Seems that this can't be fixed using the regular detection method as that depends on a PlayercontrollerB instance, which doesn't exist upon death.

I think an acceptable compromise is using the CauseOfDeath attribute as there are very few cases where a body can be recovered from a drowned player, so most likely it will remain underwater. 

Worst case scenario the filters can be disabled entirely upon death, but maybe someone has a better solution?

**Comment by notrogan** [comment]
Should be fixed in latest commit
