### ISSUE TITLE
Spectator camera audio bugged

### ISSUE THREAD

**Issue by notrogan** [notrogan/FirstPersonDeath#7]
**Describe the bug**
Audio is relative to first person camera even if using spectator camera instead

**To Reproduce**
Die close to other players, but far enough for the audio to be muffled.

**Expected behavior**
Audio quality should improve when switching to the spectator camera

**Screenshots**
n/a

**Additional context**
n/a

**Comment by notrogan** [comment]
Possible fix is to change the parent of the audiolistener depending on which camera is being used

**Comment by FrostyCirno** [comment]
Had this issue as well
