### ISSUE TITLE
Masked kill causes error spam

### ISSUE THREAD

**Issue by MathiusXII** [notrogan/FirstPersonDeath#9]
This was getting spammed in the console after I got killed by a masked/mimic
I do have some mods that affect masked if those might be the problem...

[Info   : Unity Log] Called teleport function on Player
 [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FirstPersonDeath.Patches.PlayerControllerPatch.FirstPersonPatch () (at <9ff02a0c8acc4ab991a8262c9d26ee21>:IL_00ED)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)

**Comment by notrogan** [comment]
I assume that masked/mimics use a different prefab, which would explain the null reference

Should be a simple fix since masked are the only enemy type that use the "strangulation" cause of death (i think?)

I'll take a look at it in a bit

**Comment by notrogan** [comment]
fixed
